/** Embedded config templates for `ntn-roblox init` (also mirrored as root *.example). */

export const ENV_TEMPLATE = `# Secrets only — fill in values after \`ntn-roblox init\`.
# Non-secret project settings (DB IDs, universe_id, etc.): ntn-roblox.toml

# Notion integration token (Internal Integration)
NOTION_TOKEN=secret_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# Roblox Open Cloud
ROBLOX_API_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
`;

export const TOML_TEMPLATE = `# Generated by \`ntn-roblox init\`. Safe to commit — secrets belong in .env only.

[notion]
# Parent page where \`ntn-roblox create-databases\` creates the three databases
# (32-char hex ID from the page URL). Share this page with your integration first.
parent_page_id = ""
# Filled by \`ntn-roblox create-databases\`, or set manually if you create databases yourself.
dev_product_db_id = ""
game_pass_db_id   = ""
badge_db_id       = ""

[roblox]
universe_id = 1234567890
# badge_payment_source = "user"

[logging]
# level = "info"
`;
